config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :integrations
    resources :tags
  end
	
  resources :integrations

  root 'integrations#index'
end



# Unofficial List of Intercom Integrations
# Official Intercom integrations / guides from their integration list / integration docs
# Got an integration to add? File an issue or make a pull request
# Tag
#   Official      3rd party/Community      iOS      Android      Cordova      API      Bulk      CSV      Clearbit      Conversation      Data      Github      Google Analytics     How To      Import      Jira      Library      Mobile      Notification      OAuth      Phone      Python      SDK      SMS/Text      Statistics/Reporting      Test App     Transcript      Twilio      UTM      Unsubscribe      Web      Webhooks    
# Search
# Search results : 6

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/integration.rb
class Integration < ApplicationRecord
	validates :name, :links, presence: true
	has_many :taggings
	has_many :tags, through: :taggings

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :integrations, through: :taggings
  validates :name, presence: true
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :integration
  belongs_to :tag
end

app/controllers/admin/integrations_controller.rb
class Admin::IntegrationsController < ApplicationController

	def index
		@integrations = Integration.all
		@integration = Integration.new
		get_tags
	end

	def show
		get_integration_data
	end

	def new
		get_tags
		@integration = Integration.new
	end

	def create
		get_tags
		@integration = Integration.new(integration_params)
		if @integration.save
			redirect_to [:admin, @integration]
		else
			render 'new'
		end
	end

	def edit
		get_integration_data
		get_tags
	end

	def update
		get_integration_data
		get_tags

		if integration_params[:tag_ids].nil?
			Tagging.where(:integration_id => params[:id]).delete_all
		end
  		if @integration.update(integration_params)
			redirect_to [:admin, @integration]
		else
			render 'edit'
		end
	end

	def delete
	end

	def destroy
		get_integration_data
		@integration.destroy
  		redirect_to admin_integrations_path
	end


	private def get_integration_data
	  @integration = Integration.find(params[:id])
	end
	private def get_tags
	  @tags = Tag.all
	end
	
	private def integration_params
		params.require(:integration).permit(:name, :description, :links, :tag_ids => [])
  	end	
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController

	def index
	    @tags = Tag.all

	end

	def show
		get_tag_data
	end

	def new
		@tag = Tag.new
	end

	def create
		@tag = Tag.new(tag_params)
		if @tag.save
			redirect_to [:admin, @tag]
		else
			render 'new'
		end
	end

	def edit
		get_tag_data
	end

	def update
		get_tag_data
  		if @tag.update(tag_params)
			redirect_to [:admin, @tag]
		else
			render 'edit'
		end
	end

	def delete
	end

	def destroy
		get_tag_data
		@tag.destroy
  		redirect_to admin_tags_path
	end

	
	private def get_tag_data
	  @tag = Tag.find(params[:id])
	end
	
	
	private def get_tag_input_data
	
	end

	private

		def tag_params
	    params.require(:tag).permit(:name, :description)
	  end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def is_admin?
		return false
	end
	helper_method :is_admin?
end

app/controllers/integrations_controller.rb
class IntegrationsController < ApplicationController

	def index
		@integrations = Integration.all
		@integration = Integration.new
		@search = search_params

		puts @search.inspect

		get_tags
		@integrations = nil
		if @search[:text] then
			@integrations = Integration.where('integrations.name LIKE ? OR integrations.description LIKE ?', "%#{@search[:text]}%", "%#{@search[:text]}%")
		end
		if @search[:tag_ids] && @search[:tag_ids].count > 0 then
			if @integrations.nil? 
				@integrations = Integration.includes(:tags).where(:tags => {:id => @search[:tag_ids]})
			else
				@integrations = @integrations.includes(:tags).where(:tags => {:id => @search[:tag_ids]})
			end
		end
		@integrations = Integration.all if @integrations.nil?


	end

	private def get_tags
	  @tags = Tag.all
	end
	
	private def search_params
		params.require(:search).permit(:text, :tag_ids => [])
  	end	
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	def index
	    @tags = Tag.all

	end

	def show
		get_tag_data
	end

	def new
		@tag = Tag.new
	end

	def create
		@tag = Tag.new(tag_params)
		if @tag.save
			redirect_to @tag
		else
			render 'new'
		end
	end

	def edit
		get_tag_data
	end

	def update
		get_tag_data
  		if @tag.update(tag_params)
			redirect_to @tag
		else
			render 'edit'
		end
	end

	def delete
	end

	def destroy
		get_tag_data
		@tag.destroy
  		redirect_to tags_path
	end

	
	private def get_tag_data
	  @tag = Tag.find(params[:id])
	end
	
	
	private def get_tag_input_data
	
	end

	private

		def tag_params
	    params.require(:tag).permit(:name, :description)
	  end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/integrations/_form.erb
<%= @debug.inspect if @debug %>
<%= form_with model: [:admin, @integration], local: true do |form| %>
  <% if @integration.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@integration.errors.count, "error") %> prohibited
        this integration from being saved:
      </h2>
      <ul>
        <% @integration.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.label :links %> (1 link per line)<br>
    <%= form.text_area :links %>
  </p>

  <p>
    <%= form.label :tags %><br>
	<%= render '/admin/tags/tag_list', :integration => @integration, :form => form %> 
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/admin/integrations/edit.erb
<h1>Edit Integration</h1>

<%= render 'form' %>

<td><%= link_to 'Cancel', admin_integration_path(@integration) %></td>

app/views/admin/integrations/index.erb
<h1>Integrations</h1>

<td><%= link_to 'New', new_admin_integration_path %></td>


<h3 class="search"><span class="label label-default">Search results : <%= @integrations.size %></span></h3>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Tags</th>
    <th></th>
  </tr>
 
  <% @integrations.each do |integration| %>
    <tr>
      <td><%= integration.name %></td>
      <td><%= integration.description %></td>
      <td><%= integration.tags.map{|t| t.name }.join(", ") if integration.tags %></td>
      <td>
        <ul>
        <% integration.links.each_line.map{|line| line.strip}.each{|url|
          next if url.empty?
          url = "http://#{url}" if !url.starts_with?("http://","https://")
          %><li><%= link_to url, url %></li><%
        } if integration.links
        %>
        </ul>
      </td>
      <td><%= link_to 'Show', admin_integration_path(integration) %></td>
      <td><%= link_to 'Edit', edit_admin_integration_path(integration) %></td>
      <td><%= link_to 'Destroy', admin_integration_path(integration),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/admin/integrations/new.erb
<h1>New Integration</h1>

<%= render 'form' %>

<td><%= link_to 'Back', admin_integrations_path %></td>

app/views/admin/integrations/show.erb
<h1>Integration Details</h1>

<p>
  <strong>Name:</strong>
  <%= @integration.name %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @integration.description %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @integration.tags.map(&:name).join(", ") %>
</p>

<p>
  <strong>Links:</strong>
  <ul>
  <% @integration.links.each_line.map{|line| line.strip}.each{|url|
    next if url.empty?
    url = "http://#{url}" if !url.starts_with?("http://","https://")
    %><li><%= link_to url, url %></li><%
  } if @integration.links
  %>
  </ul>
</p>


<%= link_to 'Edit', edit_admin_integration_path(@integration) %> |
<%= link_to 'Back', admin_integrations_path %>

app/views/admin/tags/_form.erb
<%= form_with model: [:admin, @tag], local: true do |form| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@tag.errors.count, "error") %> prohibited
        this tag from being saved:
      </h2>
      <ul>
        <% @tag.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/admin/tags/_tag_list.erb
<ul>
	
  <% @tags.each do |tag| %>
  		<% id = "integration[tag_ids][#{tag.id}]" %>
      <li>
        	<%= form.check_box nil, {:id => id, :checked => integration.tag_ids.include?(tag.id), :name => "integration[tag_ids][]"}, tag.id, nil %>
        	<%= form.label nil, tag.name, { :for => id} %>
      </li>
  <% end %>
</ul>

app/views/admin/tags/edit.erb
<h1>Edit Tag</h1>

<%= render 'form' %>

<td><%= link_to 'Cancel', admin_tag_path(@tag) %></td>

app/views/admin/tags/index.erb
<h1>Tags</h1>

<td><%= link_to 'New', new_admin_tag_path %></td>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
  </tr>
 
  <% @tags.each do |tag| %>
    <tr>
      <td><%= tag.name %></td>
      <td><%= tag.description %></td>
      <td><%= link_to 'Show', admin_tag_path(tag) %></td>
      <td><%= link_to 'Edit', edit_admin_tag_path(tag) %></td>
      <td><%= link_to 'Destroy', admin_tag_path(tag),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/admin/tags/new.erb
<h1>New Tag</h1>

<%= render 'form' %>

<td><%= link_to 'Back', admin_tags_path %></td>

app/views/admin/tags/show.erb
<h1>Tag Details</h1>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @tag.description %>
</p>

<%= link_to 'Edit', edit_admin_tag_path(@tag) %> |
<%= link_to 'Back', admin_tags_path %>

app/views/integrations/_form.erb
<%= @debug.inspect if @debug %>
<%= form_with model: @integration, local: true do |form| %>
  <% if @integration.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@integration.errors.count, "error") %> prohibited
        this integration from being saved:
      </h2>
      <ul>
        <% @integration.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.label :links %> (1 link per line)<br>
    <%= form.text_area :links %>
  </p>

  <p>
    <%= form.label :tags %><br>
	<%= render '/tags/tag_list', :integration => @integration, :form => form %> 
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/integrations/index.erb
<div class="search_container">  
<%= form_tag("/integrations", method: "get") do %>
  <%= text_field_tag 'search[text]', @search[:text], placeholder: 'Enter search term...'%>

  <% @tags.each do |tag| %>
      <% id = "search[tag_ids][#{tag.id}]" %>
      <li>
          <%= check_box_tag "search[tag_ids][]", tag.id, @integration.tag_ids.include?(tag.id), {:id => id} %>

          <%= label_tag nil, tag.name, { :for => id} %>
      </li>
  <% end %>
  <%= submit_tag("Search") %>
<% end %>
</div>
<div class="search_results">
  <h3 class="count_container">Search results: 
    <span class="count"><%= @integrations.size %></span>
  </h3>
<% @integrations.each do |integration| %>
  <div class="row">
    <div class="tags">
        <% if integration.tags  %>
        <% integration.tags.each{|t| %>
          <span class="tag"><%= t.name %></span>
        <% } %>
        <% end %>
    </div>
    <h2 class="title"><%= integration.name %></h2>
    <h3 class="description"><%= integration.description %></h3>
    <ul>
    <% integration.links.each_line.map{|line| line.strip}.each{|url|
      next if url.empty?
      url = "http://#{url}" if !url.starts_with?("http://","https://")
      %><li><%= link_to url, url %></li><%
    } if integration.links
    %>
    </ul>
  </div>
<% end %>
</div>

app/views/integrations/show.erb
<h1>Integration Details</h1>

<p>
  <strong>Name:</strong>
  <%= @integration.name %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @integration.description %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @integration.tags.map(&:name).join(", ") %>
</p>

<p>
  <strong>Links:</strong>
  <ul>
  <% @integration.links.each_line.map{|line| line.strip}.each{|url|
    next if url.empty?
    url = "http://#{url}" if !url.starts_with?("http://","https://")
    %><li><%= link_to url, url %></li><%
  } if @integration.links
  %>
  </ul>
</p>


<%= link_to 'Edit', edit_integration_path(@integration) %> |
<%= link_to 'Back', integrations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>An Unofficial Intercom Resources Repository</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>An Unofficial Intercom Resources Repository</h1>
    <h3>Documenting guides, how-to's, apps and integrations</h3>
    <ul>
      <li>See latest apps from Intercom and 3rd parties in the <a href="https://www.intercom.com/app-store">Intercom App Store</a></li>
    </ul>

    <% if is_admin? %>
    <ul role="nav" class="admin_nav">
      <li><%= link_to 'Integration', admin_integrations_path %></li>
      <li><%= link_to 'Tags', admin_tags_path %></li>
    </ul>
    <% end %>
    <%= yield %>

  </body>
</html>

app/views/tags/_form.erb
<%= form_with model: @tag, local: true do |form| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@tag.errors.count, "error") %> prohibited
        this tag from being saved:
      </h2>
      <ul>
        <% @tag.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/tags/index.erb
<h1>Tags</h1>

<td><%= link_to 'New', new_tag_path %></td>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
  </tr>
 
  <% @tags.each do |tag| %>
    <tr>
      <td><%= tag.name %></td>
      <td><%= tag.description %></td>
      <td><%= link_to 'Show', tag_path(tag) %></td>
      <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
      <td><%= link_to 'Destroy', tag_path(tag),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/tags/show.erb
<h1>Tag Details</h1>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @tag.description %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>